/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActorKind } from './actor-kind';

/**
 * Optional primary actor associated with a run event. Present on control actions and durable agent output where a stable user or agent identity matters; omitted on routine runtime lifecycle events. 
 */
export interface ActorRef {
    'kind': ActorKind;
    /**
     * Stable actor identifier when available.
     */
    'id'?: string;
    /**
     * Display-friendly label for the actor.
     */
    'display'?: string;
}



