/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * High-level category of an event actor.
 */

export const ActorKind = {
    USER: 'user',
    AGENT: 'agent',
    SYSTEM: 'system'
} as const;

export type ActorKind = typeof ActorKind[keyof typeof ActorKind];



