/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GitHub issue label trigger. Fires on issues.labeled and resets on issues.unlabeled for the trigger label.
 */
export interface AutomationGithubIssueTrigger {
    'id': string;
    'type': AutomationGithubIssueTriggerTypeEnum;
    'enabled': boolean;
    'trigger_label': string;
    'issue_label'?: string | null;
    'comment'?: boolean;
}

export const AutomationGithubIssueTriggerTypeEnum = {
    GITHUB_ISSUE: 'github_issue'
} as const;

export type AutomationGithubIssueTriggerTypeEnum = typeof AutomationGithubIssueTriggerTypeEnum[keyof typeof AutomationGithubIssueTriggerTypeEnum];
