/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GithubIssueRunSource {
    'type': GithubIssueRunSourceTypeEnum;
    'repository': string;
    'issue_number': number;
    'issue_title': string;
    'issue_url': string;
}

export const GithubIssueRunSourceTypeEnum = {
    GITHUB_ISSUE: 'github_issue'
} as const;

export type GithubIssueRunSourceTypeEnum = typeof GithubIssueRunSourceTypeEnum[keyof typeof GithubIssueRunSourceTypeEnum];
