/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Service health check response.
 */
export interface HealthResponse {
    /**
     * Health status indicator.
     */
    'status': string;
    /**
     * Optional server mode indicator when extra operator action is required.
     */
    'mode'?: HealthResponseModeEnum;
}

export const HealthResponseModeEnum = {
    INSTALL: 'install'
} as const;

export type HealthResponseModeEnum = typeof HealthResponseModeEnum[keyof typeof HealthResponseModeEnum];


