/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Sandbox provider selected during browser install. `api_key` is required for Daytona and ignored for Docker and Azure.
 */
export interface InstallSandboxInput {
    'provider': InstallSandboxInputProviderEnum;
    'api_key'?: string;
}

export const InstallSandboxInputProviderEnum = {
    DOCKER: 'docker',
    DAYTONA: 'daytona',
    AZURE: 'azure'
} as const;

export type InstallSandboxInputProviderEnum = typeof InstallSandboxInputProviderEnum[keyof typeof InstallSandboxInputProviderEnum];


