/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface InstallObjectStoreAzureInput {
    'provider': InstallObjectStoreAzureInputProviderEnum;
    'account': string;
    'container': string;
}

export const InstallObjectStoreAzureInputProviderEnum = {
    AZURE: 'azure'
} as const;

export type InstallObjectStoreAzureInputProviderEnum = typeof InstallObjectStoreAzureInputProviderEnum[keyof typeof InstallObjectStoreAzureInputProviderEnum];


