/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Redacted summary of persisted Azure platform install choices.
 */
export interface InstallAzureSummary {
    'subscription_id': string;
    'resource_group': string;
    'location': string;
    'subnet_id': string;
    'acr_server': string;
    'sandboxd_port': number;
    'acr_credentials_saved': boolean;
}

