/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface InstallObjectStoreS3Input {
    'provider': InstallObjectStoreS3InputProviderEnum;
    'bucket': string;
    'region': string;
    'credential_mode'?: InstallObjectStoreS3InputCredentialModeEnum;
    'access_key_id'?: string;
    'secret_access_key'?: string;
}

export const InstallObjectStoreS3InputProviderEnum = {
    S3: 's3'
} as const;

export type InstallObjectStoreS3InputProviderEnum = typeof InstallObjectStoreS3InputProviderEnum[keyof typeof InstallObjectStoreS3InputProviderEnum];
export const InstallObjectStoreS3InputCredentialModeEnum = {
    RUNTIME: 'runtime',
    ACCESS_KEY: 'access_key'
} as const;

export type InstallObjectStoreS3InputCredentialModeEnum = typeof InstallObjectStoreS3InputCredentialModeEnum[keyof typeof InstallObjectStoreS3InputCredentialModeEnum];


