/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Outcome of the CLI\'s best-effort pre-run push.
 */
export interface ManifestPreRunPushOutcome {
    'type': ManifestPreRunPushOutcomeTypeEnum;
    'remote'?: string | null;
    'branch'?: string | null;
    'message'?: string | null;
    'repo_origin_url'?: string | null;
}

export const ManifestPreRunPushOutcomeTypeEnum = {
    NOT_ATTEMPTED: 'not_attempted',
    SUCCEEDED: 'succeeded',
    FAILED: 'failed',
    SKIPPED_NO_REMOTE: 'skipped_no_remote',
    SKIPPED_REMOTE_MISMATCH: 'skipped_remote_mismatch'
} as const;

export type ManifestPreRunPushOutcomeTypeEnum = typeof ManifestPreRunPushOutcomeTypeEnum[keyof typeof ManifestPreRunPushOutcomeTypeEnum];


