/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ForkSourceRef } from './fork-source-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { PreRunGitContext } from './pre-run-git-context';

/**
 * Durable workflow run specification reconstructed from run.created events.
 */
export interface RunSpec {
    'run_id': string;
    /**
     * The persisted dense `WorkflowSettings` snapshot used for a specific run. This matches the resolved run settings recorded at launch time.
     */
    'settings': { [key: string]: any; };
    'graph': { [key: string]: any; };
    'workflow_slug'?: string | null;
    'source_directory'?: string | null;
    'repo_origin_url'?: string | null;
    'base_branch'?: string | null;
    'labels': { [key: string]: string; };
    'provenance'?: { [key: string]: any; } | null;
    'manifest_blob'?: string | null;
    'definition_blob'?: string | null;
    'pre_run_git'?: PreRunGitContext | null;
    'fork_source_ref'?: ForkSourceRef | null;
    'checkpoints_disabled': boolean;
}
