/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EvaluationResult } from './evaluation-result';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationMode } from './verification-mode';

export interface ControlPerformance {
    'mode': VerificationMode;
    'f1'?: number;
    'pass_at_1'?: number;
    'evaluations': Array<EvaluationResult>;
}



