/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An available LLM model from the built-in catalog.
 */
export interface Model {
    /**
     * Unique model identifier.
     */
    'id': string;
    /**
     * Provider that serves this model.
     */
    'provider': string;
    /**
     * Human-readable model name.
     */
    'display_name': string;
    /**
     * Maximum context window size in tokens.
     */
    'context_window': number;
    /**
     * Maximum output tokens, if known.
     */
    'max_output'?: number;
    /**
     * Whether the model supports tool use.
     */
    'supports_tools': boolean;
    /**
     * Whether the model supports vision/image inputs.
     */
    'supports_vision': boolean;
    /**
     * Whether the model supports extended reasoning.
     */
    'supports_reasoning': boolean;
    /**
     * Cost per million input tokens in USD.
     */
    'input_cost_per_million'?: number;
    /**
     * Cost per million output tokens in USD.
     */
    'output_cost_per_million'?: number;
    /**
     * Estimated output tokens per second.
     */
    'estimated_output_tps'?: number;
    /**
     * Alternative names that resolve to this model.
     */
    'aliases': Array<string>;
    /**
     * Whether this is the default model for its provider.
     */
    'default': boolean;
}

