/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RetroStats } from './retro-stats';
// May contain unused imports in some cases
// @ts-ignore
import type { SmoothnessRating } from './smoothness-rating';

export interface RetroListItem {
    'run_id': string;
    'workflow_name': string;
    'goal': string;
    'timestamp': string;
    'smoothness'?: SmoothnessRating;
    'stats': RetroStats;
    'friction_point_count': number;
}



