/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckRun } from './check-run';
// May contain unused imports in some cases
// @ts-ignore
import type { RunListItemStatus } from './run-list-item-status';

export interface RunListItem {
    'id': string;
    'repo': string;
    'title': string;
    'workflow': string;
    'status': RunListItemStatus;
    'number'?: number;
    'additions'?: number;
    'deletions'?: number;
    'checks'?: Array<CheckRun>;
    'elapsed_secs'?: number;
    'elapsed_warning'?: boolean;
    'resources'?: string;
    'comments'?: number;
    'question'?: string;
    'sandbox_id'?: string;
}



