/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SettingFieldType } from './setting-field-type';

export interface SettingField {
    'key': string;
    'label': string;
    'value': string;
    'type': SettingFieldType;
    'options'?: Array<string>;
    'description'?: string;
}



