/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ToolUse } from './tool-use';

export interface StageTurn {
    'kind': StageTurnKindEnum;
    'content'?: string;
    'tools'?: Array<ToolUse>;
}

export const StageTurnKindEnum = {
    SYSTEM: 'system',
    ASSISTANT: 'assistant',
    TOOL: 'tool'
} as const;

export type StageTurnKindEnum = typeof StageTurnKindEnum[keyof typeof StageTurnKindEnum];


