/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RetroListItem } from '../models';
/**
 * RetrosApi - axios parameter creator
 */
export const RetrosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List all retros across runs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRetros: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/retros`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RetrosApi - functional programming interface
 */
export const RetrosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RetrosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List all retros across runs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRetros(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RetroListItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRetros(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RetrosApi.listRetros']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RetrosApi - factory interface
 */
export const RetrosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RetrosApiFp(configuration)
    return {
        /**
         * 
         * @summary List all retros across runs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRetros(options?: RawAxiosRequestConfig): AxiosPromise<Array<RetroListItem>> {
            return localVarFp.listRetros(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RetrosApi - object-oriented interface
 */
export class RetrosApi extends BaseAPI {
    /**
     * 
     * @summary List all retros across runs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listRetros(options?: RawAxiosRequestConfig) {
        return RetrosApiFp(this.configuration).listRetros(options).then((request) => request(this.axios, this.basePath));
    }
}

